name: Issue Label

on:
  issues:
    types: [opened, edited]

jobs:
  issue_label:
    runs-on: ubuntu-latest
    steps:
      - uses: andymckay/labeler@master
        if: startsWith(github.event.issue.title, format('feat{0} ', ':'))
        with:
          add-labels: "typ: feat"
      - uses: andymckay/labeler@master
        if: startsWith(github.event.issue.title, format('fix{0} ', ':'))
        with:
          add-labels: "type: fix"
      - uses: andymckay/labeler@master
        if: startsWith(github.event.issue.title, format('docs{0} ', ':'))
        with:
          add-labels: "type: docs"
      - uses: andymckay/labeler@master
        if: startsWith(github.event.issue.title, format('style{0} ', ':'))
        with:
          add-labels: "type: style"
      - uses: andymckay/labeler@master
        if: startsWith(github.event.issue.title, format('refactor{0} ', ':'))
        with:
          add-labels: "type: refactor"
      - uses: andymckay/labeler@master
        if: startsWith(github.event.issue.title, format('pref{0} ', ':'))
        with:
          add-labels: "type: pref"
      - uses: andymckay/labeler@master
        if: startsWith(github.event.issue.title, format('test{0} ', ':'))
        with:
          add-labels: "type: test"
      - uses: andymckay/labeler@master
        if: startsWith(github.event.issue.title, format('chore{0} ', ':'))
        with:
          add-labels: "chore"
